name: Build Windows EXE and Upload to Release

on:
    push:
        tags:
            - "v*"

permissions:
    contents: write

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.9

            - name: Install dependencies
              run: pip install -r requirements.txt pyinstaller

            - name: Build Windows EXE
              run: pyinstaller --onefile --noconsole --name rttm_editor run.py

            - name: Check File Size
              id: check_size
              run: |
                  $fileSize = (Get-Item "dist/rttm_editor.exe").length / 1GB
                  echo "File size: $fileSize GB"
                  if ($fileSize -ge 2) {
                    echo "File too large, compressing..."
                    Compress-Archive -Path dist/rttm_editor.exe -DestinationPath dist/rttm_editor.zip
                    echo "UPLOAD_FILE=dist/rttm_editor.zip" >> $GITHUB_ENV
                  } else {
                    echo "UPLOAD_FILE=dist/rttm_editor.exe" >> $GITHUB_ENV
                  }

    release:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Upload to GitHub Release
              uses: softprops/action-gh-release@v1
              with:
                  files: dist/*
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
